/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SquadsAbbrevRouteImport } from './routes/squads/$abbrev'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsAbbrevRoute = SquadsAbbrevRouteImport.update({
  id: '/squads/$abbrev',
  path: '/squads/$abbrev',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/squads/$abbrev': typeof SquadsAbbrevRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/squads/$abbrev': typeof SquadsAbbrevRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/squads/$abbrev': typeof SquadsAbbrevRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/squads/$abbrev'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/squads/$abbrev'
  id: '__root__' | '/' | '/squads/$abbrev'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SquadsAbbrevRoute: typeof SquadsAbbrevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads/$abbrev': {
      id: '/squads/$abbrev'
      path: '/squads/$abbrev'
      fullPath: '/squads/$abbrev'
      preLoaderRoute: typeof SquadsAbbrevRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SquadsAbbrevRoute: SquadsAbbrevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
